### ISSUE TITLE
Minimal client does not work when Nuxt `baseUrl` is set

### ISSUE THREAD

**Issue by zchlm** [nuxt-modules/sanity#482]
### Version
module: 1.2.1 
nuxt: 3.0.0-rc.3

## Reproduction
**Link:** 
- [x] https://stackblitz.com/edit/nuxt-sanity-3e4uqq?file=app.vue

## Config
```
export default defineNuxtConfig({
  modules: ['@nuxtjs/sanity'],
  app: {
    baseURL: '/test/',
  },
  sanity: {
    minimal: true,
    dataset: 'production',
    projectId: '',
  },
});
```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by danielroe** [comment]
Thanks for spotting this!

I've raised a PR at https://github.com/unjs/ohmyfetch/pull/113.

**Comment by danielroe** [comment]
This will be fixed in next release of `ufo`: https://github.com/unjs/ufo/pull/68.

**Comment by danielroe** [comment]
This should be resolved in the latest version of Nuxt. You can run `nuxi upgrade` to pull it in.

**Comment by zchlm** [comment]
Hey @danielroe looks like this is still an issue. Nuxt halts and no response is given when `minimal: true`.
I've updated the dependencies in the repo link provided above
